FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /src/

COPY ./requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

COPY ./src/algos.py .
COPY ./src/batch_runtime.py .

EXPOSE 8080

RUN useradd -m app
USER app

CMD ["sh", "-c", "exec python batch_runtime.py 2>&1 | tee -a /var/log/container_logs/worker/worker-$WORKERID.log"]