FROM alpine

RUN apk add --no-cache postgresql-client aws-cli curl bash

COPY backup.sh /usr/local/bin/backup.sh
COPY entrypoint.sh /entrypoint.sh
COPY restore.sh /usr/local/bin/restore.sh
RUN chmod +x /usr/local/bin/backup.sh /entrypoint.sh /usr/local/bin/restore.sh

RUN echo "*/5 * * * * /usr/local/bin/backup.sh > /proc/1/fd/1 2>&1" > /etc/crontabs/root \
    && chmod 0600 /etc/crontabs/root

ENTRYPOINT ["/entrypoint.sh"]
CMD ["crond", "-f", "-l", "2"]