{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_cpu_usage_seconds_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\".+\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_memory_usage_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx and Postgres Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{instance=\"database_node:9187\"}",
     "legendFormat": "Postgres Database"
    },
    {
     "expr": "nginx_up{instance=\"router_node:9113\"}",
     "legendFormat": "Nginx"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"simplified_expressions\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}