FROM python:3.13-slim
WORKDIR /src/

COPY ./requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

COPY ./src/CLI.py .

EXPOSE 8080

RUN useradd -m app
USER app

CMD ["sh", "-c", "exec python CLI.py 2>> /var/log/container_logs/user_interface/error.log"]