name: build/deploy resources

on: 
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Worker
      uses: docker/build-push-action@v5
      with:
        context: infrastructure-playground/core/backend
        push: true
        tags: ghcr.io/infrastructure-playground/worker:latest

    - name: Build CLI
      uses: docker/build-push-action@v5
      with:
        context: infrastructure-playground/core/frontend
        push: true
        tags: ghcr.io/infrastructure-playground/cli:latest

    - name: Build nginx-mod
      uses: docker/build-push-action@v5
      with:
        context: infrastructure-playground/nginx-config
        push: true
        tags: ghcr.io/infrastructure-playground/nginx-mod:latest

    - name: Build postgres-mod
      uses: docker/build-push-action@v5
      with:
        context: infrastructure-playground/postgres-config
        push: true
        tags: ghcr.io/infrastructure-playground/postgres-mod:latest