name: build/deploy postgres resources

on: 
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for postgres-mod
      id: meta-postgres
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/postgres-mod
        tags: |
          type=raw,value=latest

    - name: Build postgres-mod
      uses: docker/build-push-action@v5
      with:
        context: ./postgres-config
        push: true
        tags: ${{ steps.meta-postgres.outputs.tags }}