name: validate changes

on: 
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Setup Linter
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install ruff
          pip install pytest
        
      - name: Run Linter
        run: ruff check infrastructure-playground/core/backend/src infrastructure-playground/core/frontend/src

      - name: Run Backend Tests
        run: pytest infrastructure-playground/core
      
      - name: Check Terraform Formatting
        run: |
          cd infrastructure-playground/terraform
          terraform fmt -check -recursive
          cd ../..