name: validate terraform changes

on: 
  pull_request:
    branches: ["main"]
    paths:
      - 'terraform/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Formatting
        run: |
          cd infrastructure-playground/terraform
          terraform fmt -check -recursive
          cd ../..